# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0a58fe1532adbddc29b2347e999dacb57850aecd0ec92e5b17c28500b367b61c85bc1079db38ceabf8b896cf9d4be350854327642f77ec256f4562382864854

test:
  secret_key_base: 9b833276ba94e9ca108b7881f54aa133f38d78a5441a9ca4210ab38e2089b115111126aa0ff15ffed187e463daa5b4e25ed6bd4377c93db8b7724e8df2831b53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
